from pathlib import Path
import sys
p=Path(sys.argv[1]) if len(sys.argv)>1 else Path('project/app/src/main/assets/index.html')
s=p.read_text(encoding='utf-8')
if 'NORD_V39_COMBAT_POLISH' in s: raise SystemExit(0)
patch=r'''<style id="NORD_V39_COMBAT_POLISH">
.raid-run-top.nord39{align-items:center;gap:8px}.raid-run-top.nord39>.raid-heart{display:none!important}.nord39-top{width:150px;padding:7px;border:1px solid #29454d;border-radius:13px;background:#081319}.nord39-r{display:grid;grid-template-columns:15px 1fr auto;gap:5px;align-items:center;font-size:8px;margin:3px 0}.nord39-r i{height:7px;border:1px solid #33464b;border-radius:99px;background:#18242a;overflow:hidden}.nord39-r b{display:block;height:100%}.nord39-h b{background:#d85c68}.nord39-m b{background:#5f9dde}.nord39-s b{background:#57bd83}.nord39-hero{display:flex;gap:9px;padding:8px;margin-top:7px;border:1px solid #294a51;border-radius:13px;background:#08171d}.nord39-sigil{width:46px;height:46px;flex:none;display:grid;place-items:center;border:1px solid #566f72;border-radius:13px;background:#0d171d;font-size:23px}.nord39-main{flex:1;min-width:0}.nord39-main>b{display:block;color:#ead9b5;font-size:15px}.nord39-main>small{color:#7c9390;font-size:8px}.raid-battle.nord39 .raid-actions{position:static!important;display:grid!important;grid-template-columns:repeat(2,1fr)!important;gap:6px!important;margin:0!important;padding:0!important;background:none!important;border:0!important;box-shadow:none!important}.raid-battle.nord39 .raid-actions button{min-height:56px!important;padding:6px!important;border-radius:12px!important;display:grid!important;grid-template-columns:30px 1fr;grid-template-rows:auto auto;gap:2px 6px;align-items:center;text-align:left!important}.raid-battle.nord39 .raid-actions button span{grid-row:1/3;display:grid;place-items:center;font-size:20px}.raid-battle.nord39 .raid-actions button small{display:block!important;font-size:8px!important;color:#7d9390}.nord39-j{margin-top:7px;border:1px solid #263f45;border-radius:11px;background:#081419;overflow:hidden}.nord39-j>summary{list-style:none;padding:8px 10px;color:#a7b9b5;font-size:9px}.nord39-j>summary::-webkit-details-marker{display:none}
</style>
<script id="NORD_V39_COMBAT_POLISH">
(function(){
function save(){try{return JSON.parse(localStorage.getItem('nord_rpg_save_v7')||'{}')}catch(e){return {}}}
function row(c,ic,v,m){v=+v||0;m=+m||1;return '<div class="nord39-r '+c+'"><span>'+ic+'</span><i><b style="width:'+Math.max(0,Math.min(100,v/m*100))+'%"></b></i><strong>'+Math.round(v)+'/'+Math.round(m)+'</strong></div>'}
function up(){var d=save(),a=d.activeRaid||{},t=document.querySelector('.raid-run-top');if(t&&!t.classList.contains('nord39')){t.classList.add('nord39');var x=document.createElement('div');x.className='nord39-top';x.innerHTML=row('nord39-h','❤️',a.heroHp||0,a.maxHp||100)+row('nord39-m','🔷',d.mp||0,d.maxMp||50);t.appendChild(x)}var b=document.querySelector('.raid-battle');if(b&&!b.classList.contains('nord39')){b.classList.add('nord39');var h=b.querySelector('.raid-hero-mini');if(h){var z=(h.querySelector('.raid-heart')?.textContent||'').match(/(\d+)\/(\d+)/)||[],hero=document.createElement('div');hero.className='nord39-hero';hero.innerHTML='<div class="nord39-sigil">⚔️</div><div class="nord39-main"><b>'+((h.querySelector('b')||{}).textContent||d.name||'Кирилл')+'</b><small>Воин • уровень '+(d.level||1)+'</small>'+row('nord39-h','❤️',+z[1]||a.heroHp||0,+z[2]||a.maxHp||100)+row('nord39-m','🔷',d.mp||0,d.maxMp||50)+row('nord39-s','🟢',d.st||0,d.maxSt||100)+'</div>';h.replaceWith(hero)}var lg=b.querySelector('.raid-log');if(lg&&!b.querySelector('.nord39-j')){var w=document.createElement('details');w.className='nord39-j';w.innerHTML='<summary>📜 Журнал боя</summary>';lg.parentNode.insertBefore(w,lg);w.appendChild(lg)}}}
function sfx(k,v){try{var a=new Audio('sfx/'+k+'.ogg');a.volume=.34*(v||1);var p=a.play();if(p&&p.catch)p.catch(function(){})}catch(e){}}
var oa=window.raidAction;if(oa&&!window.n39a){window.n39a=1;window.raidAction=function(t){var m={attack:['sword_hit',1],power:['sword_hit',1.25],defend:['block',1],potion:['drink',1]};if(m[t])sfx(m[t][0],m[t][1]);return oa.apply(this,arguments)}}
var oe=window.raidEvent;if(oe&&!window.n39e){window.n39e=1;window.raidEvent=function(id){var m={open:'door',trap:'block',touch:'magic',pray:'magic',search:'ui_click',rest:'drink',listen:'magic',seal:'door',follow:'sword_hit',run:'footsteps'};if(m[id])sfx(m[id],.85);return oe.apply(this,arguments)}}
var os=window.showRaidStage;if(os&&!window.n39s){window.n39s=1;window.showRaidStage=function(){var r=os.apply(this,arguments);setTimeout(up,0);return r};setTimeout(up,80)}})();</script>'''
s=s.replace('</body>',patch+'</body>',1)
p.write_text(s,encoding='utf-8')
